### ISSUE TITLE
PCB Revision

### ISSUE THREAD

**Issue by ericyangyu** [UCSD-E4E/radio_collar_tracker_drone#56]
S2 pins are larger than hole.
P1 USB DP and DN need to be swapped to avoid cable crossover
Part for P1 is not a through-hole component
P3 is close to USB port

**Comment by ntlhui** [comment]
Also need to expand keepaway around all nets

**Comment by ntlhui** [comment]
Missing pullups for the I2C bus

**Comment by ntlhui** [comment]
Check Radio Serial lines for swaps

**Comment by ntlhui** [comment]
Reverse radio connector

**Comment by ntlhui** [comment]
UP_RXD on existing is the UP Core's transmit, on ttyS0

**Comment by ntlhui** [comment]
Blocking on #57

**Comment by ntlhui** [comment]
Fix to #60 here

**Comment by ntlhui** [comment]
Completed, sent out for fab
